### ISSUE TITLE
[네비게이션 바] go_router 초기 세팅

### ISSUE THREAD

**Issue by hoogom88** [Team-Weather/flutter-wea-co#144]
## 💡 Feature Issue
- go_router 세팅

## 🌿  To-do

- [ ] go_router 세팅
- [ ] 임시 화면 생성 (각 화면 이동 버튼)
- [ ] 버튼으로 각 화면 이동
