### ISSUE TITLE
[사진 크롭 화면] 기능 보완 및 리팩토링

### ISSUE THREAD

**Issue by NalaJang** [Team-Weather/flutter-wea-co#198]
## 💡 Feature Issue

- 사진 크롭 화면 기능 추가 및 리팩토링

## 🌿  To-do

- [x] toolbar title 변경
  - [x] (Android) edit photo → 텍스트 한글로 변경(Android)
  - [x] (iOS) 완료, 취소 버튼 텍스트 변경
- [x] (Android) 상단 하단 바 색상 변경
- [x] (iOS) 이미지 비율 고정을 위해 resetButton 숨기기
- [x] 예외 처리 리팩토링
