### ISSUE TITLE
[OOTD 작성/수정 화면] 기능 보완 및 리팩토링

### ISSUE THREAD

**Issue by NalaJang** [Team-Weather/flutter-wea-co#202]
## 💡 Feature Issue

OOTD 작성/수정 화면 기능 보완 및 리팩토링

## 🌿  To-do

- [x] 예외 처리 리팩토링
  - AlertUtil 사용
- [x] 로그인한 유저 이메일 받아오기
- [x] 피드 저장 확인
- [x] 수정 확인
- [x] 피드 이미지 아래 ‘어떤 코디~~’ 텍스트 제거
- [x] 화살표 버튼 디자인 변경, 패딩 수정
- [x] 크롭 ↔ 작성 화면 무한 루프 해결
