### ISSUE TITLE
[OOTD 작성/수정 화면] 버그 수정

### ISSUE THREAD

**Issue by NalaJang** [Team-Weather/flutter-wea-co#213]
## 💡 Feature Issue

OOTD 작성/수정 화면 버그 수정

## 🌿  To-do

- [x] 피드 게시 후 새 피드 작성으로 들어왔을 때, 사진에 마지막 이미지가 떠 있는 부분 확인(실기기에서 확인)
- [x] '저장' 버튼 두 번 눌리지 않도록 수정
- [x] 카메라 버튼 누른 후 뒤로 왔을 때 null error
<img width = "650" alt = "img" src = "https://github.com/Team-Weather/flutter-wea-co/assets/73895803/e62161b8-971c-4932-9bbb-05449d473808" />
