### ISSUE TITLE
[앱 설정 화면] 로그아웃, 회원탈퇴 시 화면 라우팅 및 마이페이지 접근 가능 문제

### ISSUE THREAD

**Issue by KimDonghyeok** [Team-Weather/flutter-wea-co#216]
## 💡 Feature Issue
- 로그아웃, 회원탈퇴 시 라우터 스택에 MainScreen 이 두개 생성되는 문제
- 로그아웃, 회원탈퇴 후 뒤로가기 실행 시 마이페이지로 이동되는 문제
- 로그아웃, 회원탈퇴 시 마이페이지의 유저 상태 정보 초기화 되지않는 문제

## 🌿  To-do

- [ ]  로그아웃, 회원탈퇴 시 화면 라우팅 처리
- [ ] 마이페이지 접근 가능 문제 해결
- [ ] 로그아웃, 회원탈퇴 시 마이페이지의 유저 상태 정보 초기화
