### ISSUE TITLE
[OOTD 작성/수정 화면] 이미지 2가지 타입으로 업로드

### ISSUE THREAD

**Issue by hoogom88** [Team-Weather/flutter-wea-co#231]
## 💡 Feature Issue

- 썸네일 이미지, 원본 이미지 2가지 타입으로 업로드
- 각 상황에 맞는 타입의 이미지 표시
## 🌿  To-do

- [x] Feed 모델, 썸네일 이미지 경로 추가
- [x] 이미지 리사이징
- [x] 피드 작성시, 썸네일용 이미지, 원본 이미지 업로드
- [x] 홈화면 하단 추천 OOTD, 썸네일 이미지 표시
- [x] 유저/마이/검색 페이지, 썸네일 이미지 표시
- [x] OOTD 피드화면, 썸네일 이미지 표시
- [x] OOTD 상세화면, 원본 이미지 표시
