### ISSUE TITLE
[UI 공통] 상황에 맞는 이미지(썸네일, 원본) 표시

### ISSUE THREAD

**Issue by hoogom88** [Team-Weather/flutter-wea-co#232]
## 💡 Feature Issue

- 각 상황에 맞는 타입의 이미지 표시
## 🌿  To-do

- [ ] 홈화면 하단 추천 OOTD, 썸네일 이미지 표시
- [ ] 유저/마이/검색 페이지, 썸네일 이미지 표시
- [ ] OOTD 피드화면, 원본 이미지 표시
- [ ] OOTD 상세화면, 원본 이미지 표시
